CXX = g++
CXXFLAGS = -Wall -Wextra

build:
	$(CXX) $(CXXFLAGS) poduri.cpp -o poduri
	$(CXX) $(CXXFLAGS) adrese.cpp -o adrese
	$(CXX) $(CXXFLAGS) lego.cpp -o lego

run-p1:
	./poduri

run-p2:
	./adrese

run-p3:
	./lego

run-p4:

clean:
	rm -f poduri adrese lego
